"use client";

import { motion, useInView } from "framer-motion";
import { useRef } from "react";

const services = [
  {
    number: "01",
    title: "AI Agent Deployment",
    description:
      "Intelligent AI employees that handle lead qualification, follow-ups, market analysis, and client communication around the clock. They work while you sleep.",
  },
  {
    number: "02",
    title: "Intelligent Workflows",
    description:
      "Human-orchestrated automations connecting your entire operation. From lead capture to close, every step optimized, every handoff seamless.",
  },
  {
    number: "03",
    title: "Website & Digital Presence",
    description:
      "Conversion-optimized websites that look like they cost six figures, built with AI tools that cost almost nothing. Your digital presence, elevated.",
  },
  {
    number: "04",
    title: "AI Marketing Systems",
    description:
      "Hyper-targeted campaigns across social, email, and direct mail — all generated by AI, all on brand, all performing better than anything a human team could produce.",
  },
  {
    number: "05",
    title: "Competitive Intelligence",
    description:
      "AI-powered market analysis that tells you what your competitors are doing before they do it. An information advantage in every deal.",
  },
  {
    number: "06",
    title: "Complete AI Operations",
    description:
      "CRM automation, document generation, compliance workflows, transaction coordination — a full AI-powered operating system for your brokerage.",
  },
];

export default function Solution() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section id="services" className="relative py-24 lg:py-32">
      <div ref={ref} className="max-w-6xl mx-auto px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="max-w-2xl mb-16"
        >
          <p className="text-[13px] uppercase tracking-[0.12em] text-accent font-medium mb-5">
            What We Build
          </p>
          <h2 className="text-3xl md:text-[2.75rem] font-serif font-medium leading-[1.15] tracking-tight">
            Everything a fifty-person team does. Except it&apos;s just AI.
          </h2>
          <p className="text-text-2 text-lg mt-5 leading-relaxed">
            We don&apos;t just teach you about AI. We install an AI workforce
            into your brokerage and train you to run it.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-12">
          {services.map((service, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 24 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: 0.05 + i * 0.07 }}
              className="group"
            >
              <span className="text-[13px] font-medium text-text-3 tracking-wide">
                {service.number}
              </span>
              <h3 className="text-lg font-semibold text-dark mt-2 mb-3 group-hover:text-accent transition-colors duration-300">
                {service.title}
              </h3>
              <p className="text-[15px] text-text-2 leading-relaxed">
                {service.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
